# Generated by Django 3.1 on 2020-08-19 12:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.SmallIntegerField(default='', verbose_name='Local id')),
                ('google_id', models.CharField(default='', max_length=200, verbose_name='Google ID')),
                ('lat', models.CharField(default='', max_length=50, verbose_name='Latitude')),
                ('lng', models.CharField(default='', max_length=50, verbose_name='Longitude')),
                ('name', models.CharField(default='', max_length=200, verbose_name="Nom de l'emplacement")),
                ('address', models.CharField(default='', max_length=200, verbose_name="Adresse de l'emplacement")),
                ('place_type', models.CharField(choices=[('CP', 'Camping'), ('BV', 'Bivouac'), ('PT', 'Particulier'), ('GT', 'Gîte'), ('HT', 'Hotel')], default='CP', max_length=2, verbose_name='Type de lieu')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Moyenne des notes')),
                ('user_ratings_total', models.SmallIntegerField(default='0', verbose_name='Nombre total de votes')),
                ('phone_number', models.CharField(default=0, max_length=10, verbose_name='Numéro de téléphone')),
                ('website', models.CharField(default='', max_length=200, verbose_name='Site web')),
                ('opening_hour', models.TimeField(default=datetime.time(0, 0), verbose_name="Horaires d'ouverture")),
                ('closing_hour', models.TimeField(default=datetime.time(0, 0), verbose_name='Horaires de fermeture')),
            ],
        ),
        migrations.CreateModel(
            name='Camping',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='randoMap.place')),
                ('restauration', models.BooleanField(default=False)),
                ('bike_shopping', models.BooleanField(default=False)),
            ],
            bases=('randoMap.place',),
        ),
        migrations.CreateModel(
            name='Openings',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='randoMap.place')),
                ('monday', models.CharField(default='', max_length=30, verbose_name='Hoaraires du lundi')),
                ('tuesday', models.CharField(default='', max_length=30, verbose_name='Hoaraires du mardi')),
                ('wednesday', models.CharField(default='', max_length=30, verbose_name='Hoaraires du mercredi')),
                ('thursday', models.CharField(default='', max_length=30, verbose_name='Hoaraires du jeudi')),
                ('friday', models.CharField(default='', max_length=30, verbose_name='Hoaraires du vendredi')),
                ('saturday', models.CharField(default='', max_length=30, verbose_name='Hoaraires du samedi')),
                ('sunday', models.CharField(default='', max_length=30, verbose_name='Hoaraires du dimanche')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiffre', models.SmallIntegerField(verbose_name='Note entre 0 et 5')),
                ('place', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='randoMap.place')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
